### ISSUE TITLE
Add remove method to DB API

### ISSUE THREAD

**Issue by Zettersten** [ncb000gt/pinned#8]
The backed rewrite looks great. I didn't noticed a delete or remove method. Is this because we need to update the entire doc to be without the data we wish to remove? I think there is room here for some sort of remove method. Perhaps we don't actually remove the data but instead do something DARI like to hide it from the doc response?

 Thoughts?

**Comment by ncb000gt** [comment]
Herp.

**Comment by ncb000gt** [comment]
8e17996
